### ISSUE TITLE
TorbJörn: Turret Health

### ISSUE THREAD

**Issue by DpsDoomMain** [MaxwellJung/ow1_emulator_issues#230]
In Overwatch One Torbjörn’s turret had 250 hp now it has 225 can probably fix the same way you fixed Ashe

**Comment by MaxwellJung** [comment]
I thought it was 250, but i'll double check that number.

**Comment by DpsDoomMain** [comment]
Don’t know just guessing

**Comment by MaxwellJung** [comment]
Please make sure your issue is correct before submitting one. OW1 torbjorn turret had 250 hp
